### ISSUE TITLE
Test token refresh with and without scopes

### ISSUE THREAD

**Issue by jmandel** [onc-healthit/inferno#246]
During token refresh, the SMART App Launch spec states that a `scope` parameter is optional -- i.e., that the client may include or omit it. Inferno should test both ways to ensure that servers can handle the presence + absence of this `scope` parameter. (We've seen servers in the wild that only work in one case or the other, so it'd be good to catch this in testing.)

**Comment by arscan** [comment]
Thanks @jmandel, we are working on this in PR #248.

There are a couple of minor discrepancies between the initial [access token code exchange](http://hl7.org/fhir/smart-app-launch/#step-3-app-exchanges-authorization-code-for-access-token) and the [token refresh](http://hl7.org/fhir/smart-app-launch/#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token) that we now see.  We are updating the test to reflect this differences, but let me know if I'm misreading the spec because I wasn't expecting them:
* The `expires_in` property is required in the token refresh response, but is only recommended in the access token exchange.
* The access token exchange requires `Pragma` and `Cache-Control` headers in the response, but the refresh token exchange does not

**Comment by jmandel** [comment]
Thanks @arscan for the response + close read.

Re: `expires_in` property and `Pragma` + `Cache-Control` headers, it looks to me like the spec should have made all three required for all access token responses (irrespective of `grant_type`). It's a good issue for us to take up in the next SMART App Launch publication, and I've created https://github.com/HL7/smart-app-launch/issues/293 to capture it (though I'll note we don't currently have an update in-progress).

In the meantime, I suppose a good behavior for Inferno would be to follow the spec as currently written when generating formal errors (which is slightly weaker than ideal), and perhaps generate warnings in the other cases.
