### ISSUE TITLE
Implantable Device Test USCID-09 is expecting both Device.udiCarrier.carrierAIDC and Device.udiCarrier.carrierHRF

### ISSUE THREAD

**Issue by fhirczar** [onc-healthit/inferno#456]
The Implantable Device Test USCID-09 is expecting both Device.udiCarrier.carrierAIDC and Device.udiCarrier.carrierHRF when the US Core FHIR spec indicates that each Device must support "A Unique Device Identifier (UDI) numeric or alphanumeric code either as the Human Readable Form (HRF) string representation of the barcode or the Automatic Identification and Data Capture (AIDC) representation."  

We are receiving "Error Message: Could not find Device.udiCarrier.carrierAIDC" when the query results include Device.udiCarrier.carrierHRF but not Device.udiCarrier.carrierAIDC.  

Both  Device.udiCarrier.carrierAIDC and Device.udiCarrier.carrierHRF should not be required to meet this test.  It should expect one or the other.

http://hl7.org/fhir/us/core/StructureDefinition-us-core-implantable-device.html#mandatory-and-must-support-data-elements

[device_payload.txt](https://github.com/onc-healthit/inferno/files/4690758/device_payload.txt)

**Comment by czh-orz** [comment]
Thanks for submitting this issue. You are correct that each device must contain either a carrierAIDC or carrierHRF. However, since both are "must support" in the device profile, we must verify if the server is capable of supplying both. This means the test expects to see at least two devices, one with carrierAIDC and one with carrierHRF.

**Comment by fhirczar** [comment]
We will make the above changes and include at least two devices during our tests.  Closing issue.
