### ISSUE TITLE
Community tests for resources needing references are not passing when there seems to be reference, example patient endpoint ran with Organization reference, then Organization says there was no reference. 

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#512]
https://inferno.healthit.gov/community/gfFzoukAaDP/

This is the instance showing the execution of the Patient and passing on the Community, but the Organization does not pass saying reference not found in prior searches.   

![Inferno-referenceissue](https://user-images.githubusercontent.com/66788141/101839129-72b1d900-3b07-11eb-887a-0a8434fdb4de.png)

**Comment by yunwwang** [comment]
Inferno saves reference with "must-support" flag for later testing. The following US Core profiles have “Must Support” data element which reference Organization resources:

CareTeam
DiagnosticReport Lab
DiagnosticReport Note
DocumentReference
MedicationRequest
Provenance

In order to run Organization test sequence, the Organization resources have to be referenced in at least one of those US core resources.

**Comment by healthland** [comment]
Ok, thanks for that update.  We were used to when we were testing before the updates and it just had to have a reference and it would work.  Thank you!

**Comment by healthland** [comment]
I have another question on knowing what these "must-support" data elements are for a resource.  Such as we are testing the Encounter recourse now and it doesn't seem like any profiles are "Must Support".  Thank you!

**Comment by radamson** [comment]
No problem, I'll try and explain, but let me know if I'm misunderstanding your question!

These resources, like Encounter, have no searches or are not explicitly required in [USCDI](https://www.healthit.gov/isa/united-states-core-data-interoperability-uscdi).  That being said, some other resources do reference these profiles on a must-support element.

e.g. for [US Core DiagnosticReport Note](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-diagnosticreport-note.html) the `DiagnosticReport.encounter` is must-support and references US Core Encounter.

![Screen Shot 2020-12-18 at 3 44 45 PM](https://user-images.githubusercontent.com/41651655/102659767-fa22cc00-4147-11eb-8397-8e551d4ae814.png)

Thus if any DiagnosticReports are seen with an Encounter reference, those references will be resolved and tested in the US Core Encounter Sequence.

The US Core PractitionerRole tests will be removed in 2.11.0 because they are not referenced by any profile (see the updated sequence list [here](https://github.com/onc-healthit/inferno/blob/73aa1a822546dc7cb860d4d7bf5d3de9b1383c0c/lib/modules/uscore_v3.1.1_module.yml#L43))

_Side Note: the US Core Encounter tests here really should have other tests for the required searches and not rely on references from other profiles._

**Comment by healthland** [comment]
Thank you!  That answered my question perfectly.  Thanks for all your help.  This ticket may be closed.  Merry Christmas!
